/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.StudentController;
import java.util.ArrayList;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Students;

/**
 *
 * @author JayJomJohn
 */
public class StudentInformation extends javax.swing.JFrame {

    public StudentInformation() {
        initComponents();
        showTable();
        Disable();
    }

    public void showTable() {
        StudentController studentController = new StudentController();
        ArrayList<Students> list = studentController.displayStudents();

        DefaultTableModel model = (DefaultTableModel) tbl_studentsList.getModel();
        model.setRowCount(0);
        Object[] row = new Object[6];

        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getId();
            row[1] = list.get(i).getName();
            row[2] = list.get(i).getEmail();
            row[3] = list.get(i).getPassword();
            row[4] = list.get(i).getGender();
            row[5] = list.get(i).getAddress();
            model.addRow(row);
            totalrecords.setText("Total Records # : " + tbl_studentsList.getRowCount());

        }

    }

    private void Disable() {
        txt_name.setEnabled(false);
        txt_email.setEnabled(false);
        txt_pass.setEnabled(false);
        txt_address.setEnabled(false);
        radio_male.setEnabled(false);
        radio_female.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        iconified = new javax.swing.JLabel();
        systemExit = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_studentsList = new rojerusan.RSTableMetro();
        jLabel1 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_address = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        totalrecords = new javax.swing.JLabel();
        txt_pass = new javax.swing.JPasswordField();
        radio_male = new javax.swing.JRadioButton();
        radio_female = new javax.swing.JRadioButton();
        txt_email = new javax.swing.JTextField();
        btn_delete = new rojerusan.RSMaterialButtonRectangle();
        btn_insert = new rojerusan.RSMaterialButtonRectangle();
        btn_update = new rojerusan.RSMaterialButtonRectangle();
        btn_clear = new rojerusan.RSMaterialButtonRectangle();
        btn_new = new rojerusan.RSMaterialButtonRectangle();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CRUD");
        setMaximumSize(new java.awt.Dimension(980, 550));
        setMinimumSize(new java.awt.Dimension(980, 550));
        setUndecorated(true);
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 33)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 102, 0));
        jLabel4.setText("STUDENT INFORMATION");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 420, 30));

        iconified.setFont(new java.awt.Font("Arial Black", 1, 30)); // NOI18N
        iconified.setForeground(new java.awt.Color(255, 255, 255));
        iconified.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconified.setText("-");
        iconified.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconifiedMouseClicked(evt);
            }
        });
        jPanel1.add(iconified, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 10, 20, 30));

        systemExit.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        systemExit.setForeground(new java.awt.Color(255, 255, 255));
        systemExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        systemExit.setText("X");
        systemExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                systemExitMouseClicked(evt);
            }
        });
        jPanel1.add(systemExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, 20, 30));

        tbl_studentsList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STUDENT_ID", "STUDENT_NAME  ", "STUDENT_EMAIL", "STUDENT_PASSWORD", "STUDENT_GENDER", "STUDENT_ADDRESS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_studentsList.setColorBackgoundHead(new java.awt.Color(204, 102, 0));
        tbl_studentsList.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tbl_studentsList.setColorFilasForeground1(new java.awt.Color(204, 102, 0));
        tbl_studentsList.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tbl_studentsList.setColorSelBackgound(new java.awt.Color(0, 51, 102));
        tbl_studentsList.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbl_studentsList.setFuenteFilas(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbl_studentsList.setFuenteFilasSelect(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbl_studentsList.setFuenteHead(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tbl_studentsList.getTableHeader().setReorderingAllowed(false);
        tbl_studentsList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_studentsListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_studentsList);
        if (tbl_studentsList.getColumnModel().getColumnCount() > 0) {
            tbl_studentsList.getColumnModel().getColumn(0).setResizable(false);
            tbl_studentsList.getColumnModel().getColumn(1).setResizable(false);
            tbl_studentsList.getColumnModel().getColumn(2).setResizable(false);
            tbl_studentsList.getColumnModel().getColumn(3).setResizable(false);
            tbl_studentsList.getColumnModel().getColumn(4).setResizable(false);
            tbl_studentsList.getColumnModel().getColumn(5).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 910, 200));

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 102, 0));
        jLabel1.setText("STUDENT ID:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 120, 30));

        txt_id.setEditable(false);
        txt_id.setBackground(new java.awt.Color(0, 0, 0));
        txt_id.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_id.setForeground(new java.awt.Color(204, 102, 0));
        txt_id.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 110, -1));

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 102, 0));
        jLabel2.setText("NAME:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 100, 30));

        txt_name.setBackground(new java.awt.Color(0, 0, 0));
        txt_name.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_name.setForeground(new java.awt.Color(204, 102, 0));
        txt_name.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 180, -1));

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 102, 0));
        jLabel3.setText("EMAIL:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 100, 30));

        txt_address.setBackground(new java.awt.Color(0, 0, 0));
        txt_address.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_address.setForeground(new java.awt.Color(204, 102, 0));
        txt_address.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(txt_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 520, -1));

        jLabel5.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 102, 0));
        jLabel5.setText("PASSWORD:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 110, 30));

        jLabel7.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 102, 0));
        jLabel7.setText("GENDER:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 110, 30));

        totalrecords.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        totalrecords.setForeground(new java.awt.Color(204, 102, 0));
        totalrecords.setText("Total Records # :");
        jPanel1.add(totalrecords, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 150, 20));

        txt_pass.setBackground(new java.awt.Color(0, 0, 0));
        txt_pass.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_pass.setForeground(new java.awt.Color(204, 51, 0));
        txt_pass.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(txt_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 180, 30));

        radio_male.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(radio_male);
        radio_male.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        radio_male.setForeground(new java.awt.Color(204, 51, 0));
        radio_male.setText("Male");
        radio_male.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(radio_male, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, -1, 30));

        radio_female.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(radio_female);
        radio_female.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        radio_female.setForeground(new java.awt.Color(204, 51, 0));
        radio_female.setText("Female");
        radio_female.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(radio_female, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, -1, 30));

        txt_email.setBackground(new java.awt.Color(0, 0, 0));
        txt_email.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_email.setForeground(new java.awt.Color(204, 102, 0));
        txt_email.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 180, -1));

        btn_delete.setBackground(new java.awt.Color(204, 51, 0));
        btn_delete.setText("delete");
        btn_delete.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        jPanel1.add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 260, 110, 40));

        btn_insert.setBackground(new java.awt.Color(204, 51, 0));
        btn_insert.setText("insert");
        btn_insert.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btn_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertActionPerformed(evt);
            }
        });
        jPanel1.add(btn_insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, 110, 40));

        btn_update.setBackground(new java.awt.Color(204, 51, 0));
        btn_update.setText("update");
        btn_update.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        jPanel1.add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, 110, 40));

        btn_clear.setBackground(new java.awt.Color(204, 51, 0));
        btn_clear.setText("clear");
        btn_clear.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        jPanel1.add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 260, 110, 40));

        btn_new.setBackground(new java.awt.Color(204, 51, 0));
        btn_new.setText("new");
        btn_new.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btn_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newActionPerformed(evt);
            }
        });
        jPanel1.add(btn_new, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 110, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 910, 10));

        jLabel9.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 102, 0));
        jLabel9.setText("ADDRESS:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 100, 30));

        getContentPane().add(jPanel1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void iconifiedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconifiedMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_iconifiedMouseClicked

    private void systemExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_systemExitMouseClicked
        for (double i = 1.0; i >= 0.0; i = i - 0.1) {
            String val = i + "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try {
                Thread.sleep(30);
            } catch (Exception e) {

            }
        }

        System.exit(0);
    }//GEN-LAST:event_systemExitMouseClicked

    private void btn_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newActionPerformed
        txt_name.setEnabled(true);
        txt_email.setEnabled(true);
        txt_pass.setEnabled(true);
        txt_address.setEnabled(true);
        radio_male.setEnabled(true);
        radio_female.setEnabled(true);
        txt_name.requestFocus();
    }//GEN-LAST:event_btn_newActionPerformed

    private void showClear() {
        txt_id.setText("");
        txt_name.setText("");
        txt_pass.setText("");
        txt_email.setText("");
        txt_address.setText("");
        buttonGroup1.clearSelection();
    }

    private void insertStudent() {
        String name = txt_name.getText().toUpperCase();
        String email = txt_email.getText();
        String pass = txt_pass.getText();
        radio_male.setActionCommand("Male");
        radio_female.setActionCommand("Female");
        String gen = buttonGroup1.getSelection().getActionCommand();
        String address = txt_address.getText();

        model.Students users = new Students();
        users.setName(name);
        users.setEmail(email);
        users.setPassword(pass);
        users.setGender(gen);
        users.setPassword(pass);
        users.setAddress(address);

        //CONTROLLER SAVE
        StudentController studentController = new StudentController();
        studentController.saveInformation(users);

        //REFRESHDATA
        showTable();
        JOptionPane.showMessageDialog(rootPane, "Has been Created");

        //CLEARTEXT
        showClear();
    }

    private void btn_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertActionPerformed

        if (txt_name.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Name cannot be empty", "ATTENTION", JOptionPane.ERROR_MESSAGE);
            getToolkit().beep();
            txt_name.requestFocus();

        } else if (!Pattern.matches("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$", txt_email.getText())) {
            JOptionPane.showMessageDialog(null, "Please enter a valid email", "Error", JOptionPane.ERROR_MESSAGE);
            getToolkit().beep();
            txt_email.requestFocus();

        } else if (txt_pass.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Password cannot be empty", "ATTENTION", JOptionPane.ERROR_MESSAGE);
            getToolkit().beep();
            txt_pass.requestFocus();

        } else if (txt_address.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Address cannot be empty", "ATTENTION", JOptionPane.ERROR_MESSAGE);
            getToolkit().beep();
            txt_address.requestFocus();

        } else if (radio_male.isSelected() == false && radio_female.isSelected() == false) {
            JOptionPane.showMessageDialog(rootPane, "Gender cannot be empty", "ATTENTION", JOptionPane.ERROR_MESSAGE);
            getToolkit().beep();

        } else {
            insertStudent();
        }

    }//GEN-LAST:event_btn_insertActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed

        int id = Integer.parseInt(txt_id.getText());
        String name = txt_name.getText().toUpperCase();
        String email = txt_email.getText();
        String pass = txt_pass.getText();
        radio_male.setActionCommand("Male");
        radio_female.setActionCommand("Female");
        String gen = buttonGroup1.getSelection().getActionCommand();
        String address = txt_address.getText();

        if (txt_name.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Name cannot be empty", "ATTENTION", JOptionPane.ERROR_MESSAGE);
            getToolkit().beep();
            txt_name.requestFocus();

        } else if (!Pattern.matches("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$", txt_email.getText())) {
            JOptionPane.showMessageDialog(null, "Please enter a valid email", "Error", JOptionPane.ERROR_MESSAGE);
            getToolkit().beep();
            txt_email.requestFocus();

        } else if (txt_pass.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Password cannot be empty", "ATTENTION", JOptionPane.ERROR_MESSAGE);
            getToolkit().beep();
            txt_pass.requestFocus();

        } else if (txt_address.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Address cannot be empty", "ATTENTION", JOptionPane.ERROR_MESSAGE);
            getToolkit().beep();
            txt_address.requestFocus();

        } else if (radio_male.isSelected() == false && radio_female.isSelected() == false) {
            JOptionPane.showMessageDialog(rootPane, "Gender cannot be empty", "ATTENTION", JOptionPane.ERROR_MESSAGE);
            getToolkit().beep();

        } else {

            model.Students users = new Students();
            users.setName(name);
            users.setEmail(email);
            users.setPassword(pass);
            users.setGender(gen);
            users.setPassword(pass);
            users.setAddress(address);
            users.setId(id);

            //CONTROLLER UPDATE
            StudentController studentController = new StudentController();
            studentController.updateInformation(users);

            //REFRESHDATA
            showTable();
            JOptionPane.showMessageDialog(rootPane, "Has been Updated!");

            //CLEARTEXT
            showClear();

        }

    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        showClear();
        showTable();
        JOptionPane.showMessageDialog(rootPane, "Cleared");
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed

        Boolean id = !txt_id.getText().isEmpty();

        if (id) {
            model.Students users = new Students();
            users.setId(Integer.parseInt(txt_id.getText()));

            //CONTROLLER DELETE
            StudentController studentController = new StudentController();
            studentController.deleteInformation(users);

            //REFRESHDATA
            showTable();
            JOptionPane.showMessageDialog(rootPane, "Has been Deleted!");

            //CLEARTEXT
            showClear();
        } else {

            JOptionPane.showMessageDialog(rootPane, "Please Select a index row and delete properly");
        }

    }//GEN-LAST:event_btn_deleteActionPerformed

    public void getInformation(int index) {
        StudentController studentController = new StudentController();
        txt_id.setText(Integer.toString(studentController.displayStudents().get(index).getId()));
        txt_name.setText(studentController.displayStudents().get(index).getName());
        txt_email.setText(studentController.displayStudents().get(index).getEmail());
        txt_pass.setText(studentController.displayStudents().get(index).getPassword());

        String gen = studentController.displayStudents().get(index).getGender();
        if ("Male".equals(gen)) {
            radio_male.setSelected(true);

        } else if ("Female".equals(gen)) {
            radio_female.setSelected(true);
        }
        txt_address.setText(studentController.displayStudents().get(index).getAddress());
    }

    private void tbl_studentsListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_studentsListMouseClicked
        int index = tbl_studentsList.getSelectedRow();
        getInformation(index);
    }//GEN-LAST:event_tbl_studentsListMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle btn_clear;
    private rojerusan.RSMaterialButtonRectangle btn_delete;
    private rojerusan.RSMaterialButtonRectangle btn_insert;
    private rojerusan.RSMaterialButtonRectangle btn_new;
    private rojerusan.RSMaterialButtonRectangle btn_update;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel iconified;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton radio_female;
    private javax.swing.JRadioButton radio_male;
    private javax.swing.JLabel systemExit;
    private rojerusan.RSTableMetro tbl_studentsList;
    private javax.swing.JLabel totalrecords;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_name;
    private javax.swing.JPasswordField txt_pass;
    // End of variables declaration//GEN-END:variables
}
